plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'io.absolutwarehouse'
version = '0.1'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'com.fasterxml.jackson.core:jackson-core:2.17.2'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.17.2'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'

    implementation 'org.postgresql:postgresql:42.6.0'
}

test {
    useJUnitPlatform()
}

application {
    // nouvelle syntaxe recommandée par Gradle 8+
    mainClass = 'io.absolutwarehouse.Main'
}

tasks.register('serverRun', JavaExec) {
    mainClass = 'io.absolutwarehouse.Main'
    classpath = sourceSets.main.runtimeClasspath
}

jar {
    manifest {
        attributes(
                'Main-Class': 'io.absolutwarehouse.Main'
        )
    }
}

// pour s'assurer que le shadowJar utilise ton manifest
shadowJar {
    mergeServiceFiles()
    manifest {
        attributes(
                'Main-Class': 'io.absolutwarehouse.Main'
        )
    }
}
